---
apiVersion: v1
kind: ConfigMap
metadata:
  name: maya-config
data:
  maya.properties: |
    api.ui.index=https://${URL}/ui/latest
    server."default".access.grant=true
    maya.api.ui.enabled=true
    api.auth.enabler=github_user:${AuthENABLER}
    api.auth.github.client.id=${GITHUBCLIENTID}
    api.auth.github.client.secret=${GITHUBCLIENTSECRET}
    no.reply.email.address=${EMAILADRESS}
    no.reply.email.password=${EMAILPASS}
    slack.config.bot.client.id=${botclientid}
    slack.config.bot.client.secret=${botclientsecret}
    slack.config.bot.oauth.url=https://slack.com/oauth/authorize?client_id=${botclientid}&scope=bot\,incoming-webhook\,commands
    slack.notification.welcome.message=Hello\, this is a welcome message from your MuleBot at MayaOnline. This channel will be updated with Alert messages from your OpenEBS clusters. You can use /maya command to query the configuration and status of your clusters.
    mayaUrl=https://${URL}
    maya.ingress.gke=/mayastore/maya-ingress-gke.yaml
    maya.ingress.auth=/mayastore/auth
    maya.cortex.push.url=https://${URL}/maya-cortex-push/api/prom/push
    maya.cortex.pull.url=https://${URL}/maya-cortex-pull/api/prom
    maya.cortex.configs.url=https://${URL}/maya-cortex-configs/api/prom/configs/rules
    maya.cortex.am.url=https://${URL}/maya-cortex-am/api/prom/alertmanager/
    maya.grafana.url=http://maya-grafana-service."default".svc.cluster.local:3000/
    maya.grafana.reporter.url=http://maya-grafana-service."default".svc.cluster.local:8686/
    maya.kibana.url=http://kibana-logging."default".svc.cluster.local:5601/
    maya.elasticsearch.url=http://elasticsearch-logging."default".svc.cluster.local:9200/
    maya.mdape2e.url=http://openebs-ci-client-service."default".svc.cluster.local:80/
    maya.grafana.admin.password=admin
    mulebot.alert.url=https://${URL}/chat-server/maya-events
    maya.alertstore.tablemanager.url=http://alertstore-tablemanager."default".svc.cluster.local/
    maya.alertstore.ingress.url=https://${URL}/alertstore/alerts
    maya.alertstore.url=http://alertstore."default".svc.cluster.local/
    maya.killbill.server.url=http://killbill-server."default".svc.cluster.local:8080
    maya.killbill.admin.username=admin
    maya.killbill.admin.password=MayaOnline@123
    maya.killbill.mayaonline.tenant.api.key=mayaonline
    maya.killbill.mayaonline.tenant.api.secret=MayaOnline@123
    sales.email.address=support@mayadata.io
    maya.dmaas.cloud.agent.url=http://cloud-agent-service."default".svc.cluster.local:8880
    maya.setup.name=mayaonline-staging
    maya.billing.type=external
    backend.feature.analytics.google.code=UA-127388617-2
    external.svc.unauthorize.redirect.url=https://${URL}/login
    feature.dmaas.disable=true
    api.auth.external.provider.configured=true
    api.github.scheme=https://
    api.auth.access.mode=unrestricted
    api.auth.user.type=github_user
    api.auth.external.provider.identity.separator=,
    api.auth.provider.configured=githubconfig\,googleconfig
    api.security.enabled=true
    api.auth.allowed.identities=:
    api.auth.google.client.id=15778894521-se7i6mruap5qcpkl8cd4k4jgigvp6eoq.apps.googleusercontent.com
    api.auth.google.client.secret=pjXCoE-EXK8_h55XsYzcMPrN
---
