apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: maya-ui
spec:
  selector:
    matchLabels:
      app: maya-ui
  template:
    metadata:
      labels:
        app: maya-ui
    spec:
      containers:
      - image: mayadataio/maya-ui:staging-a37f5aaf
        imagePullPolicy: Always
        name: maya-ui
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        env:
        - name: VENDOR
          value: "dop"
        volumeMounts:
        - name: config-data
          mountPath: /tmp/mo-vendor
      imagePullSecrets:
      - name: {{ .Values.server.dockerSecret }}
      volumes:
        - name: config-data
          hostPath:
            path: /tmp/mo-vendor

