apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-claim
spec:
  storageClassName: cstor-storage-class
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40G

