apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-maya-io
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: crb-maya-io
  namespace: default
subjects:
- kind: ServiceAccount
  name: sa-maya-io
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

