apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mayastore
  namespace: {{ .Values.server.namespace }}
spec:
  storageClassName: {{ .Values.mayastore.storageClass }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mayastore.storageCapacity }}

