apiVersion: v1
kind: Service
metadata:
  name: alertstore-tablemanager
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    name: alertstore-tablemanager

