apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: maya-grafana
  name: maya-grafana
  namespace: {{ .Values.mod.namespace }}
spec:
  template:
    metadata:
      labels:
        app: maya-grafana
    spec:
      containers:
      - image: index.docker.io/mayadata/graph-reporter:1.0.0-RC1.ee
        name: grafana-reporter
        imagePullPolicy: Always
        ports:
        - containerPort: 8686
      - env:
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "false"
        image: index.docker.io/mayadata/maya-grafana:1.0.0-RC1.ee
        imagePullPolicy: Always
        name: master-grafana
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /etc/grafana
          name: config-volume
        - mountPath: /var/lib/grafana
          name: maya-grafana-store
      securityContext:
        fsGroup: 107
        runAsUser: 104
      imagePullSecrets:
      - name: {{ .Values.mod.dockersecret }}
      volumes:
      - configMap:
          name: maya-grafana-cfgmap
        name: config-volume
      - name: maya-grafana-store
        persistentVolumeClaim:
          claimName: grafana-claim

