apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mayastore
  namespace: variablename
spec:
  storageClassName: cstor-storage-class
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40G

