apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mayastore
  namespace: {{ .Values.mod.namespace }}
spec:
  storageClassName: {{ .Values.mayastore.storageclass }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40G

