apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat-server
  name: chat-server
  namespace: {{ .Values.mod.namespace }}
spec:
  ports:
  - name: maya-chatops
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: chat-server

