# Default values for DirectorOnPrem.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

server:
  release: 1.1.0-ee
  dockerSecret: directoronprem-registry-secret
  protocol: http
  url: 192.168.99.61:30380
  httpNodePort: 30380
  httpsNodePort: 30381
  apiAuthAccessMode: unrestricted
  serverDefaultAccessGrant: true
  apiUiEnabled: true
  setupName: directoronprem
  apiAuthExternalProviderEnabled: false
  apiAuthExternalProviderConfigured:
  apiAuthInternalProviderEnabled: true
  apiAuthInternalProviderConfigured: localAuthConfig
  apiAuthEnabler:
  apiAuthGithubClientId:
  apiAuthGithubClientSecret:
  apiAuthGoogleClientId:
  apiAuthGoogleClientSecret:
  clusterDomain: cluster.local
  featureSubscriptionDisable: false
  subscriptionType: internal
  featureBillingDisable: true
  billingType: external
  featureEmailDisable: true
  senderEmailAddress:
  senderEmailPassword:
  featureDocsDisable: false
  docsUrl: https://docs.mayaonline.io
  featureChatBotDisable: true
  slackConfigBotClientId:
  slackConfigBotClientSecret:
  slackNotificationWelcomeMessage:
  featureKialiDisable: true
  analyticsGoogleCode:
  autoconnectLocalCluster: true

mysql:
  #storageClass: openebs-jiva-default
  storageClass: openebs-hostpath
  storageCapacity: 10Gi

elasticSearch:
  #storageClass: openebs-hostpath
  storageClass: openebs-hostpath
  storageCapacity: 10Gi
  replicas: 1

cassandra:
  #storageClass: openebs-hostpath
  storageClass: openebs-hostpath
  storageCapacity: 10Gi
  replicas: 1

mayaStore:
  #storageClass: cstor-storage-class
  storageClass: openebs-hostpath
  storageCapacity: 1Gi

grafana:
  #storageClass: cstor-storage-class
  storageClass: openebs-hostpath
  storageCapacity: 10Gi

cortex:
  replicationFactor: 1
  timeout: 5s

alertStore:
  replicationFactor: 1

ingester:
  replicas: 1

querier:
  replicas: 1


